version: "3.7"
services:
  producer:
    image: clojure:openjdk-8-lein
    volumes:
      - "./producer:/producer"
    working_dir: /producer
    command: lein run

  database:
    image: postgres:11
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root123
    ports:
      - "5432"
