version: "3.7"
services:
  front-end:
    image: nodejs:12
    container_name: clomplete-front-end
    volumes:
      - "./front-end:/front-end"
    working_dir: /front-end
    command: npm start
    ports:
      - "3000:3000"
  producer:
    image: clojure:openjdk-8-lein
    container_name: clomplete-producer
    volumes:
      - "./producer:/producer"
    working_dir: /producer
    command: lein run
    depends_on:
      - database
    environment:
      DATABASE_HOST: "database"
      DATABASE_PORT: "5432"
      DATABASE_NAME: "clomplete"
      DATABASE_USER: "root"
      DATABASE_PASSWORD: "root123"
  consumer:
    image: clojure:openjdk-8-lein
    container_name: clomplete-consumer
    volumes:
      - "./consumer:/consumer"
    working_dir: /consumer
    command: tail -F xxx
    depends_on:
      - database
    environment:
      DATABASE_HOST: "database"
      DATABASE_PORT: "5432"
      DATABASE_NAME: "clomplete"
      DATABASE_USER: "root"
      DATABASE_PASSWORD: "root123"
  database:
    image: postgres:11
    container_name: clomplete-database
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root123
    ports:
      - "5432:5432"
# kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:5.3.1
    hostname: zookeeper
    container_name: clomplete-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  broker:
    image: confluentinc/cp-enterprise-kafka:5.3.1
    hostname: broker
    container_name: clomplete-broker
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_METRIC_REPORTERS: io.confluent.metrics.reporter.ConfluentMetricsReporter
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CONFLUENT_METRICS_REPORTER_BOOTSTRAP_SERVERS: broker:29092
      CONFLUENT_METRICS_REPORTER_ZOOKEEPER_CONNECT: zookeeper:2181
      CONFLUENT_METRICS_REPORTER_TOPIC_REPLICAS: 1
      CONFLUENT_METRICS_ENABLE: 'true'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'
  control-center:
    container_name: clomplete-control-center
    image: confluentinc/cp-enterprise-control-center:5.3.1
    hostname: control-center
    container_name: control-center
    depends_on:
      - zookeeper
      - broker
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'broker:29092'
      CONTROL_CENTER_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021